name: Build Snap Template

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: Enable Corepack for pnpm
        run: |
          corepack enable
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build snap-template for core22
        run: |
          bash packages/snap-template/build.sh core22
      - name: Build snap-template for core24
        run: |
          bash packages/snap-template/build.sh core24
      - name: Run tests for snap-template
        run: |
          bash packages/snap-template/build.sh test
      - name: Upload snap-templates artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: snap-templates-linux
          path: packages/snap-template/out/**/*.tar.gz
          if-no-files-found: error
          retention-days: 1
          