name: Build Snap Template

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup LXD for snapcraft
        uses: canonical/setup-lxd@main
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build snap-template for amd64
        shell: bash
        run: |
          bash packages/snap-template/build.sh amd64
      - name: Build snap-template for arm64
        shell: bash
        run: |
          bash packages/snap-template/build.sh arm64
      - name: Run tests for snap-template
        shell: bash
        run: |
          bash packages/snap-template/build.sh test
      - name: Upload snap-templates artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: snap-templates-linux
          path: packages/snap-template/out/**/*.tar.gz
          if-no-files-found: error
          retention-days: 1
          