name: Build AppImage

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  mac:
    runs-on: ${{ matrix.node }}
    strategy:
      fail-fast: false
      matrix:
        node: [macos-15-intel, macos-15]
    steps:
      - name: Enable Corepack for pnpm
        run: |
          corepack enable
          brew install desktop-file-utils meson tree
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build for macOS
        run: bash ./build.sh
        shell: bash
        working-directory: ./packages/appimage
        env: { TARGET: darwin }

      - name: Upload appimage artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: appimage-temp-macos-${{ matrix.node }}
          path: packages/appimage/out/**/*.zip
          if-no-files-found: error
          retention-days: 1

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Enable Corepack for pnpm
        run: |
          corepack enable
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build for Linux
        run: bash ./build.sh
        shell: bash
        working-directory: ./packages/appimage
        env: { TARGET: linux }

      - name: Download runtime
        run: bash ./build.sh
        shell: bash
        working-directory: ./packages/appimage
        env: { TARGET: runtime }

      - name: Upload appimage artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: appimage-temp-linux
          path: packages/appimage/out/**/*.zip
          if-no-files-found: error
          retention-days: 1

  combine-artifacts:
    runs-on: ubuntu-latest
    needs: [mac, linux]
    steps:
      - name: Enable Corepack for pnpm
        run: |
          corepack enable
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
     
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }
     
      - name: Download all appimage artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          pattern: appimage-temp-*
          path: packages/appimage/out
          merge-multiple: true

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Zip bundle
        run: bash packages/appimage/build.sh
        shell: bash
        env: { TARGET: compress }

      - name: Delete all previous build stage artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          name: appimage-temp-*

      - name: Upload combined artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
        with:
          name: appimage-bundle
          if-no-files-found: error
          path: packages/appimage/out/**/*.zip
          retention-days: 1