name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write # to create release (changesets/action)
  pull-requests: write # to create pull request (changesets/action)
  attestations: write # to create attestation during publish step (@actions/attest)
  id-token: write # to create OIDC token for attestation

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yaml

  release:
    runs-on: macos-latest
    needs: build-artifacts
    timeout-minutes: 15
    steps:
      - name: Checkout code repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Download new artifacts
        id: download-artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          artifact-ids: ${{ needs.build-artifacts.outputs.artifactId }}

      - name: Display structure of downloaded files
        run: ls -R artifacts-staging

      - name: Enable Corepack for pnpm
        run: |
          corepack enable
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
        with: { node-version: '22' }
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
      
      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@06245a4e0a36c064a573d4150030f5ec548e4fcc # v1.4.1
        with:
          version: "pnpm ci:version"
          publish: "pnpm ci:publish"
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create scoped releases
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo "Releases created with tags: ${{ steps.changesets.outputs.publishedPackages }}"
          node scripts/changeset-publish.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}

      
